/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"


GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *quit2;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *viewport;
 GtkWidget *statusbar;
 GtkWidget *fixed1;
  GtkWidget *scrolledwindow2;
  GtkWidget *globalLabel;

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainWindow, "mainWindow");
  gtk_object_set_data (GTK_OBJECT (mainWindow), "mainWindow", mainWindow);
  gtk_window_set_title (GTK_WINDOW (mainWindow), "Etherpeg");
  gtk_window_set_default_size (GTK_WINDOW (mainWindow), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainWindow), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar, "menubar");
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (menubar), 1);

  file = gtk_menu_item_new_with_label ("File");
  gtk_widget_set_name (file, "file");
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_set_name (file_menu, "file_menu");
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  quit2 = gtk_menu_item_new_with_label ("Quit");
  gtk_widget_set_name (quit2, "quit2");
  gtk_widget_ref (quit2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "quit2", quit2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit2);
  gtk_container_add (GTK_CONTAINER (file_menu), quit2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);

  viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport, "viewport");
  gtk_widget_ref (viewport);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "viewport", viewport,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport);

  fixed1 = gtk_fixed_new ();
  gtk_widget_set_name (fixed1, "fixed1");
  gtk_widget_ref (fixed1);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "fixed1", fixed1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (viewport), fixed1);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_ref (statusbar);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "statusbar", statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox2), statusbar, FALSE, FALSE, 0);

  globalLabel = gtk_label_new ("Global");
  gtk_widget_set_name (globalLabel, "globalLabel");
  gtk_widget_ref (globalLabel);
  gtk_object_set_data_full (GTK_OBJECT (mainWindow), "globalLabel", globalLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (globalLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), globalLabel);

  gtk_signal_connect (GTK_OBJECT (file), "activate",
                      GTK_SIGNAL_FUNC (on_file1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit2), "activate",
                      GTK_SIGNAL_FUNC (on_quit2_activate),
                      NULL);

  return mainWindow;
}

